server/api/api/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include('apps.api.urls', namespace='api')),
    url(r'', include('apps.main.urls', namespace='main')),
    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^patients/', include('apps.patients.urls', namespace='patients')),
    url(r'^med_tests/', include('apps.med_tests.urls', namespace='med_tests')),
    url(r'^appointments/', include('apps.appointments.urls', namespace='appointments')),
    url(r'^diagnosis/', include('apps.diagnosis.urls', namespace='diagnosis')),
    url(r'^reports/', include('apps.reports.urls', namespace='reports')),
    url(r'^analytics/', include('apps.analytics.urls', namespace='analytics'))
]

server/api/apps/api/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

from apps.api.views import *
from apps.api.views.patients_views import PatientListView

urlpatterns = (
    # Create account
    url(r'^account$', SignupView.as_view(), name='account'),

    # Users
    url(r'^users$', UserListView.as_view(), name='users'),
    url(r'^user/(?P<pk>\d+)$', UserView.as_view(), name='user'),
    url(r'^user/check_login', check_login, name='check_login'),

    # Areas
    url(r'^areas$', MedAreaListView.as_view(), name='areas'),
    url(r'^area/(?P<pk>\d+)$', MedAreaView.as_view(), name='area'),

    # Tests
    url(r'^tests$', MedTestListView.as_view(), name='tests'),
    url(r'^test/(?P<pk>\d+)$', MedTestView.as_view(), name='test'),

    # Real Inds
    url(r'^real_inds$', RealIndListView.as_view(), name='real_inds'),
    url(r'^real_ind/(?P<pk>\d+)', RealIndView.as_view(), name='real_ind'),

    # Int Inds
    url(r'^int_inds$', IntIndListView.as_view(), name='int_inds'),
    url(r'^int_ind/(?P<pk>\d+)', IntIndView.as_view(), name='int_ind'),

    # Text Inds
    url(r'^text_inds$', TextIndListView.as_view(), name='text_inds'),
    url(r'^text_ind/(?P<pk>\d+)', TextIndView.as_view(), name='text_ind'),

    # Test Records
    url(r'^test_recs/(?P<patient_id>\d+)/(?P<test_type_id>.+)', csrf_exempt(TestRecListView.as_view()), name='test_recs'),

    # Patients
    url(r'^patients$', login_required(PatientListView.as_view()), name='patients')
)

server/api/apps/main/urls.py
from django.conf.urls import url
from apps.main.views import *

urlpatterns = [
    url(r'^$', index_view, name='index'),
    url(r'^about$', about_view, name='about'),
    url(r'^help$', help_view, name='help'),
    url(r'^login$', login_view, name='login'),
    url(r'^help/med_tests/(?P<test_id>\d+)$', show_med_test_help, name='show_med_test_help'),
    url(r'^help/med_tests$', med_tests_help, name='med_tests_help'),
    url(r'^on_fail/login$', on_fail_login, name='on_fail_login')
]

server/api/apps/users/urls.py
from django.conf.urls import url
from apps.users.views import *

urlpatterns = [
    url(r'^show$', show_action, name='show'),
    url(r'^create$', create_action, name='create'),
    url(r'^update$', update_action, name='update'),
    url(r'^change_password$', change_password_action, name='change_password'),
    url(r'^reset_password$', reset_password_action, name='reset_password'),
    url(r'^delete$', delete_action, name='delete'),
    url(r'^logout$', logout_action, name='logout'),
    url(r'^dashboard$', dashboard_action, name='dashboard')
]

server/api/apps/main/models.py
from django.db import models

# Create your models here.

server/api/apps/main/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse

from apps.core.models import MedTest


def index_view(request):
    if request.user is not None and request.user.is_active:
        return redirect(reverse('patients:list'))
    return render(request, 'main/index.html', {})


def about_view(request):
    return render(request, 'main/about.html', {})


def help_view(request):
    return render(request, 'main/help.html', {})


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request=request, user=user)
                if user.is_superuser and user.role == 'ADMIN':
                    return redirect(reverse('admin:index'))
                return redirect(reverse('patients:list'))
    return redirect(reverse('main:index'))


@login_required
def med_tests_help(request):
    med_tests = MedTest.objects.all()
    return render(request, 'main/med_tests_help.html', {'med_tests': med_tests})


@login_required
def show_med_test_help(request, test_id):
    med_test = MedTest.objects.get(pk=test_id)
    return render(request, 'main/med_test_help.html', {'med_test': med_test})


def on_fail_login(request):
    return render(request, 'main/login.html', {})

server/api/templates/main/about.html
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>О сайте</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}"/>
</head>
<body style="padding-top: 70px;">
<div class="container">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <div class="navbar-brand">LaksmiMed</div>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'main:index' %}">Главная</a></li>
                <li><a href="">О сайте</a></li>
                <li><a href="">Юридическая информация</a></li>
                <li><a href="">Помощь</a></li>
            </ul>
        </div>
    </nav>
    <div class="row">
        <h2>Цель проекта</h2>
    </div>
    <div class="row">
        <p class="lead">
            Наша задача заключается в создании удобного и мощного инструмента для врачей, нуждающихся в повышении эффективности
            каждодневной работы с медицинскими картами и учетом пациентов, статистической обработки
            медицинских обследований с целью выявления закономерностей в возникновении тех или иных заболеваний.
            Конечная цель нашего проекта - сделать диагностирование быстрым и безошибочным.
        </p>
    </div>
    <div class="row">
        <p class="lead">
            Данный веб-сайт выполнен в рамках курсовой работы и является одним из проектов единой
            системы интеграции медицины и информационных технологий
            <br/>
            Ссылки на другие проекты:
            <br/>
            Химия для медицины: <a href="http://chem-for-med.ru">http://chem-for-med.ru</a>
        </p>
    </div>
    <div class="row">
        <h2>Руководители проекта</h2>
    </div>
    <div class="row">
        <p class="lead">
            Кузьмичева Г.М. –– доктор химических наук, профессор, Лаборатория рентгеновских методов
            исследования, <a href="https://chemtech.mirea.ru/department/office-of-science-intensive-chemical-technologies/mitts/">Кафедра материаловедения и технологии функциональных материалов и структур</a>,
            <a href="https://www.mirea.ru">Московский технологический университете (МИРЭА, МГУПИ, МИТХТ)</a>
            <br/>
            Подбельский В.В. –– доктор физико-математических наук, профессор, Департамент программной инженерии,
            <a href="https://cs.hse.ru">Факультет компьютерных наук</a>, <a href="https://www.hse.ru">НИУ "Высшая школа экономики"</a>
        </p>
    </div>
    <div class="row">
        <h2>Разработка</h2>
    </div>
    <div class="row">
        <p class="lead">
            © Ярных Р.В., 2017 (все права защищены)<br/>
            Организация: <a href="https://cs.hse.ru">Факультет компьютерных наук</a>, <a href="https://www.hse.ru">НИУ "Высшая школа экономики"</a>
            <br/>
            Адрес электронной почты: <a href="mailto:egdeveloper@mail.ru">egdeveloper@mail.ru</a>
            <br/>
            Проект размещен в свободном доступе на github: <a href="https://github.com/reactmed/reactmed">https://github.com/reactmed/reactmed</a>
        </p>
    </div>
</div>
<script type="text/javascript" src="{% static 'jquery/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

server/api/templates/main/help.html
{% extends 'core/base_menu.html' %}
{% load staticfiles %}
{% block header %}
    <style>
        body {
            padding-top: 40px;
        }

        .screenshot {
            margin: 30px auto;
        }
    </style>
{% endblock %}
{% block content %}
    <h2 class="page-header">
        Ознакомительные видео
    </h2>
    <h3>
        Как пользоваться сайтом
    </h3>
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://youtube.com/embed/QLOjVrzF7qQ?rel=0"
                allowfullscreen></iframe>
    </div>
    <h3>
        Как пользоваться панелью администратора
    </h3>
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://youtube.com/embed/BV7iwj9mZZI?rel=0"
                allowfullscreen></iframe>
    </div>
    <h2 class="page-header">
        Работа с картами пациентов
    </h2>
    <p class="lead">
        Вы можете создавать новые карты пациентов и редактировать их,
        следить за состоянием пациента и контролировать динамику
    </p>
    <h3>Создание карты пациента</h3>
    <p class="lead">Чтобы создать карту пациента, Вы должны на странице с таблицой пациентов
        нажать на кнопку "Добавить пациента" и перейти на новую страницу.
    </p>
    <img class="screenshot" src="{% static 'img/core/help_add_patient.png' %}" style="width: 100%; height: auto;">
    <p class="lead">На данной странице Вам необходимо ввести ФИО пациента, пол и дату рождения. Поля "Адрес" и "Род
        деятельности"
        необязательны для заполнения. Также необходимо указать номер полиса обязательного медицинского страхования
        (ОМС), чтобы
        уникально идентифицировать пациента в базе данных.
    </p>
    <img class="screenshot" src="{% static 'img/core/help_save_patient.png' %}" style="width: 100%; height: auto;">
    <p class="lead">
        После нажатия на "Сохранить медкарту пациента" запись о пациенте создается в БД и Вы можете
        посмотреть ее. Для этого Вам нужно нажать на главном меню "Пациенты", выбрать в боком меню "Пациенты"
        и нажать на кнопку "Открыть" в виде зеленого квадрата с пером в строке интересующего пациента
    </p>
    <img class="screenshot" src="{% static 'img/core/help_open_patient.png' %}">
{% endblock %}

{% block scripts %}

{% endblock %}

server/api/templates/main/index.html
{% load staticfiles %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Добро пожаловать!</title>
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}"/>
        <style>
            .carousel-caption {
                display: inline-block;
                vertical-align: middle;
                text-align: center;
                background-color: rgba(0, 0, 0, 0.5);
            }

            .nav-tabs {
                margin-bottom: 15px;
            }

            code {
                font-size: 80%;
            }

            .marketing h2 {
                font-weight: normal;
            }

            .marketing .span4 p {
                margin-left: 10px;
                margin-right: 10px;
            }

            body {
                padding-bottom: 40px;
                color: #5a5a5a;
                min-width: 100%;
                width: auto !important;
            }
        </style>
    </head>
    <body style="padding-top: 50px;">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <div class="navbar-brand">ReactMed</div>
                </div>
                <ul class="nav navbar-nav">
                    <li><a href="/">Главная</a></li>
                    <li><a href="{% url 'main:about' %}">О сайте</a></li>
                    <li><a href="">Юридическая информация</a></li>
                    <li><a href="">Помощь</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#" data-toggle="modal" data-target="#login-modal">Войти</a></li>
                </ul>
            </div>
        </nav>
        <div class="container">
            <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog modal-md">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title" id="myModalLabel">Войти</h4>
                        </div>
                        <div class="modal-body">
                            <div class="row">
                                <div style="padding-right: 30px; padding-left: 5px">
                                    <ul class="nav nav-tabs">
                                        <li class="active"><a href="#login" data-toggle="tab">Войти</a></li>
                                    </ul>
                                    <div class="tab-content">
                                        <div class="tab-pane active">
                                            <form id="id_login_form" action="{% url 'main:login' %}"
                                                  class="form-horizontal" method="post">
                                                {% csrf_token %}
                                                <div class="form-group">
                                                    <label class="col-sm-2 control-label">Логин</label>
                                                    <div class="col-sm-10">
                                                        <div class="input-group">
                                                    <span class="input-group-addon">
                                                        <i class="glyphicon glyphicon-user"></i>
                                                    </span>
                                                            <input id="id_login" class="form-control" placeholder="Логин"
                                                                   name="username"/>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label class="col-sm-2 control-label">Пароль</label>
                                                    <div class="col-sm-10">
                                                        <div class="input-group">
                                                    <span class="input-group-addon">
                                                        <i class="glyphicon glyphicon-lock"></i>
                                                    </span>
                                                            <input type="password" class="form-control"
                                                                   id="id_password" placeholder="Пароль"
                                                                   name="password"/>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row pull-right">
                                                    <button id="login-btn" type="button" onclick="tryLogin();" class="btn btn-primary btn-sm">
                                                        Войти
                                                    </button>
                                                    <a id="sign-up-btn" type="button" class="btn btn-primary btn-sm"
                                                       href="{% url 'users:create' %}">
                                                        Регистрация
                                                    </a>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <a href="{% url 'users:reset_password' %}">Забыли пароль?</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <header id="slideShow" class="carousel slide">
            <ol class="carousel-indicators" style="margin-top: 10px;">
                <li data-target="#slideShow" data-slide-to="0" class="active"></li>
                <li data-target="#slideShow" data-slide-to="1"></li>
                <li data-target="#slideshow" data-slide-ti="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img src="{% static 'img/healthcare-banner.jpg' %}" style="height: 500px; width: 1440px;"/>
                    <div class="carousel-caption">
                        <h2>
                            ReactMed - сервис для работы с медицинскими картами пациентов
                            и статистической обработки медицинских данных для постановки диагноза и проведения
                            исследований
                            <br/>
                        </h2>
                        <a class="btn btn-lg btn-primary" href="#" data-toggle="modal" data-target="#login-modal"
                           role="button">Войти</a>
                    </div>
                </div>
                <div class="item">
                    <img src="{% static 'img/slider-img.jpg' %}" style="height: 500px; width: 1440px;"/>
                    <div class="carousel-caption">
                        <h2>
                            Контролируйте поток пациентов, отслеживайте динамику их здоровья, составляйте отчеты с
                            возможностью прикрепления к анализам
                            необходимый контент
                        </h2>
                    </div>
                </div>
                <div class="item">
                    <img src="{% static 'img/slider4.jpg' %}" style="height: 500px; width: 1440px;"/>
                    <div class="carousel-caption">
                        <h2>
                            Коммуницируйте с другими врачами, следите за статистическими сводками и своевременно
                            диагностируйте
                            заболевания
                        </h2>
                    </div>
                </div>
            </div>
            <a class="left carousel-control" href="#slideShow" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#slideShow" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </header>
        <script type="text/javascript" src="{% static 'jquery/jquery.js' %}"></script>
        <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'bootbox/bootbox.js' %}"></script>
        <script type="text/javascript">
{#            $("#slideShow").carousel({interval: 5000});#}
        </script>
        <script>
            function tryLogin() {
                var username = $('#id_login').val();
                var password = $('#id_password').val();
                $.get('{% url 'api:check_login' %}', {
                    username: username,
                    password: password
                }, function (resp) {
                   if(resp && resp.error){
                       bootbox.alert({
                          message: resp.error
                       });
                   }
                   else{
                       $('#id_login_form').submit();
                   }
                });
            }
        </script>
    </body>
</html>

server/api/templates/main/login.html
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}">
        <style>
            .myForm {
                min-width: 500px;
                position: absolute;
                text-align: center;
                top: 50%;
                left: 50%;
                transform: translate(-50%, -50%);
                font-size: 2.5rem
            }
        </style>
    </head>
    <body style="padding-top: 90px">
        <div class="container">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Вход
                </div>
                <div class="panel-body">
                    <form id="id_login_form" action="{% url 'main:login' %}"
                          class="form-horizontal" method="post">
                        {% csrf_token %}
                        <div class="form-group row">
                            <label class="col-sm-2 control-label">Логин</label>
                            <div class="col-sm-10">
                                <div class="input-group">
                                                    <span class="input-group-addon">
                                                        <i class="glyphicon glyphicon-user"></i>
                                                    </span>
                                    <input id="id_login" class="form-control" placeholder="Логин"
                                           name="username"/>
                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-2 control-label">Пароль</label>
                            <div class="col-sm-10">
                                <div class="input-group">
                                                    <span class="input-group-addon">
                                                        <i class="glyphicon glyphicon-lock"></i>
                                                    </span>
                                    <input type="password" class="form-control"
                                           id="id_password" placeholder="Пароль"
                                           name="password"/>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    <div class="form-group row">
                        <div class="col-md-8">

                        </div>
                        <div class="col-md-2">
                            <button id="login-btn" style="width: 100%" type="button" onclick="login();"
                                    class="btn btn-primary btn-sm">
                                Войти
                            </button>
                        </div>
                        <div class="col-md-2">
                            <button id="sign-up-btn" style="width: 100%" type="button" class="btn btn-primary"
                                    onclick="window.location='{% url 'users:create' %}'">
                                Регистрация
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script src="{% static 'jquery/jquery.js' %}">

        </script>
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}">

        </script>
        <script src="{% static 'bootbox/bootbox.js' %}"></script>
        <script>
            function login() {
                var username = $('#id_login').val();
                var password = $('#id_password').val();
                $.get('{% url 'api:check_login' %}', {
                    username: username,
                    password: password
                }, function (resp) {
                    if (resp && resp.error) {
                        bootbox.alert({
                            message: resp.error
                        });
                    }
                    else {
                        $('#id_login_form').submit();
                    }
                });
            }
        </script>
    </body>
</html>

server/api/templates/main/med_test_help.html
{% extends 'core/base_menu.html' %}
{% load staticfiles %}
{% block header %}
    <style>
        body {
            padding-top: 90px;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="panel panel-primary">
        <div class="panel-heading">
            Основная информация
        </div>
        <div class="panel-body">
            <form>
                <div class="form-group row">
                    <label class="col-md-2 control-label">Тип обследования</label>
                    <div class="col-md-4">
                        <input class="form-control" value="{{ med_test.name }}">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-2 control-label">Медицинская область</label>
                    <div class="col-md-4">
                        <input class="form-control" value="{{ med_test.med_area.name }}">
                    </div>
                </div>
            </form>
        </div>
    </div>
    {% if med_test.real_inds.count != 0 %}
        <div class="panel panel-primary">
            <div class="panel-heading">
                Вещественные показатели
            </div>
            <div class="panel-body">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Показатель</th>
                            <th>Минимальная норма</th>
                            <th>Максимальная норма</th>
                            <th>Единица измерения</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for ind in med_test.real_inds.all %}
                            <tr>
                                <td>{{ ind.name }}</td>
                                <td>{{ ind.min_norm|default_if_none:"-" }}</td>
                                <td>{{ ind.max_norm|default_if_none:"-" }}</td>
                                <td>{{ ind.unit|default_if_none:"-" }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% endif %}
    {% if med_test.int_inds.count != 0 %}
        <div class="panel panel-primary">
            <div class="panel-heading">
                Целые показатели
            </div>
            <div class="panel-body">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Показатель</th>
                            <th>Минимальная норма</th>
                            <th>Максимальная норма</th>
                            <th>Единица измерения</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for ind in med_test.int_inds.all %}
                            <tr>
                                <td>{{ ind.name }}</td>
                                <td>{{ ind.min_norm|default_if_none:"-" }}</td>
                                <td>{{ ind.max_norm|default_if_none:"-" }}</td>
                                <td>{{ ind.unit|default_if_none:"-" }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% endif %}
    {% if med_test.text_inds.count != 0 %}
        <div class="panel panel-primary">
            <div class="panel-heading">
                Строковые показатели
            </div>
            <div class="panel-body">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Показатель</th>
                            <th>Принимаемые значения</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for ind in med_test.text_inds.all %}
                            <tr>
                                <td>{{ ind.name }}</td>
                                <td>{{ ind.values|default_if_none:"-"|join:", " }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% endif %}
{% endblock %}

server/api/templates/main/med_tests_help.html
{% extends 'core/base_menu.html' %}
{% load staticfiles %}
{% block header %}
    <style>
        body{
            padding-top: 90px;
        }
    </style>
{% endblock %}
{% block content %}
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Тип обследования</th>
                <th>Медицинская область</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            {% for test in med_tests %}
                <tr>
                    <td>{{ test.name }}</td>
                    <td>{{ test.med_area.name }}</td>
                    <td>
                        <button class="btn btn-success" onclick="window.location='{% url 'main:show_med_test_help' test_id=test.id %}'">Открыть справку</button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}