server/api/api/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include('apps.api.urls', namespace='api')),
    url(r'', include('apps.main.urls', namespace='main')),
    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^patients/', include('apps.patients.urls', namespace='patients')),
    url(r'^med_tests/', include('apps.med_tests.urls', namespace='med_tests')),
    url(r'^appointments/', include('apps.appointments.urls', namespace='appointments')),
    url(r'^diagnosis/', include('apps.diagnosis.urls', namespace='diagnosis')),
    url(r'^reports/', include('apps.reports.urls', namespace='reports')),
    url(r'^analytics/', include('apps.analytics.urls', namespace='analytics'))
]

server/api/apps/analytics/urls.py
from django.conf.urls import url
from apps.analytics.views import *

urlpatterns = [
    url(r'^visualize$', visualize_action, name='visualize'),
    url(r'^cluster$', cluster_action, name='cluster'),
    url(r'^data$', data_action, name='data'),
    url(r'^data/features/stat$', features_stat_action, name='features_stat'),
    url(r'^datasets$', datasets_page_action, name='datasets'),
    url(r'^visualization$', visualize_page_action, name='visualization'),
    url(r'^clustering$', clustering_page_action, name='clustering')
]

server/api/apps/main/urls.py
from django.conf.urls import url
from apps.main.views import *

urlpatterns = [
    url(r'^$', index_view, name='index'),
    url(r'^about$', about_view, name='about'),
    url(r'^help$', help_view, name='help'),
    url(r'^login$', login_view, name='login'),
    url(r'^help/med_tests/(?P<test_id>\d+)$', show_med_test_help, name='show_med_test_help'),
    url(r'^help/med_tests$', med_tests_help, name='med_tests_help'),
    url(r'^on_fail/login$', on_fail_login, name='on_fail_login')
]

server/api/apps/patients/urls.py
from django.conf.urls import url

from apps.patients.views import *

urlpatterns = [
    url(r'^list$', list_action, name='list'),
    url(r'^tests$', tests_action, name='tests'),
    url(r'^appointments$', appointments_action, name='appointments'),
    url(r'^create$', create_action, name='create'),
    url(r'^update$', update_action, name='update'),
    url(r'^show/(?P<patient_id>\d+)$', show_action, name='show'),
    url(r'^delete/(?P<patient_id>\d+)$', delete_action, name='delete'),
    url(r'(?P<patient_id>\d+)/tests$', patient_test_action, name='patient_tests'),
    url(r'(?P<patient_id>\d+)/dynamics$', patient_dynamics_action, name='patient_dynamics'),
    url(r'(?P<patient_id>\d+)/appointments$', patient_appointments_action, name='patient_appointments'),
    url(r'(?P<patient_id>\d+)/diagnosis$', patient_diagnosis_action, name='patient_diagnosis'),
]

server/api/apps/users/urls.py
from django.conf.urls import url
from apps.users.views import *

urlpatterns = [
    url(r'^show$', show_action, name='show'),
    url(r'^create$', create_action, name='create'),
    url(r'^update$', update_action, name='update'),
    url(r'^change_password$', change_password_action, name='change_password'),
    url(r'^reset_password$', reset_password_action, name='reset_password'),
    url(r'^delete$', delete_action, name='delete'),
    url(r'^logout$', logout_action, name='logout'),
    url(r'^dashboard$', dashboard_action, name='dashboard')
]

server/api/apps/core/models.py
# -*- coding: utf-8 -*- 
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.contrib.postgres.fields import *
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _
from transliterate import translit
from datetime import date, timedelta
from django.conf import settings

from apps.core.managers import UserManager

GENDER = (
    ('Мужской', 'Мужской'),
    ('Женский', 'Женский')
)

BLOOD_GROUP = (
    ('I', 'I'),
    ('II', 'II'),
    ('III', 'III'),
    ('IV', 'IV')
)

RH_FACTOR = (
    ('Rh+', 'Rh+'),
    ('Rh-', 'Rh-')
)

APPOINTMENT_STATUS = (
    ('Назначено', 'Назначено'),
    ('Завершено', 'Завершено'),
    ('Отменено', 'Отменено')
)

DIAGNOSIS_TYPE = (
    ('Предварительный', 'Предварительный'),
    ('Клинический', 'Клинический'),
    ('Окончательный', 'Окончательный')
)

USER_ROLES = (
    ('ADMIN', 'ADMIN'),
    ('DOCTOR', 'DOCTOR')
)


class AbstractModel(models.Model):
    id = models.AutoField(primary_key=True)

    class Meta:
        abstract = True


class User(AbstractBaseUser, PermissionsMixin):
    email = models.CharField(verbose_name=_('Email'), max_length=30, unique=True)
    name = models.CharField(verbose_name=_('Имя'), max_length=30)
    surname = models.CharField(verbose_name=_('Фамилия'), max_length=30)
    patronymic = models.CharField(verbose_name=_('Отчество'), max_length=30, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(_('Администратор?'), default=False)
    date_joined = models.DateTimeField(default=now())
    role = models.CharField(verbose_name=_('Роль'), max_length=20, choices=USER_ROLES, default='DOCTOR')

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        db_table = 'user'
        verbose_name = _('Пользователь')
        verbose_name_plural = _('Пользователи')

    def get_short_name(self):
        return '%s %s' % (self.name, self.surname)

    def get_full_name(self):
        return '%s' % self.name


class Address(AbstractModel):
    post_code = models.CharField(max_length=30, verbose_name='Post code')
    country = models.CharField(max_length=100, verbose_name='Country')
    region = models.CharField(max_length=100, verbose_name='Region')
    city = models.CharField(max_length=100, verbose_name='City')
    street = models.CharField(max_length=150, verbose_name='Street')

    class Meta:
        db_table = 'address'
        verbose_name = _('Address')
        verbose_name_plural = _('Addresses')


class OmiCard(AbstractModel):
    number = models.CharField(max_length=16, verbose_name='Number')
    expire_date = models.DateField(verbose_name='Expiration date')
    insurance_org = models.CharField(max_length=150, verbose_name='Insurance Organization')

    class Meta:
        db_table = 'omi_card'
        verbose_name = _('OMI Card')
        verbose_name_plural = _('OMI Cards')


class Patient(AbstractModel):
    name = models.CharField(verbose_name=_('Имя'), max_length=50)
    surname = models.CharField(verbose_name=_('Фамилия'), max_length=50)
    patronymic = models.CharField(verbose_name=_('Отчество'), max_length=50, blank=True, null=True)
    gender = models.CharField(verbose_name=_('Пол'), max_length=20, choices=GENDER)
    birthday = models.DateField(verbose_name=_('Дата рождения'))
    blood_group = models.CharField(verbose_name=_('Группа крови'), max_length=20, choices=BLOOD_GROUP, blank=True,
                                   null=True)
    rh_factor = models.CharField(verbose_name=_('Резус-фактор'), max_length=20, choices=RH_FACTOR, blank=True, null=True)
    is_disabled = models.BooleanField(verbose_name=_('Инвалидность'), default=False)
    omi_card = models.CharField(verbose_name=_('ОМС'), max_length=30, blank=True, null=True)
    address = models.CharField(verbose_name=_('Адрес проживания'), max_length=255, blank=True, null=True)
    occupation = models.CharField(verbose_name=_('Род деятельности'), max_length=100, blank=True, null=True)
    doctor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='patients', on_delete=models.CASCADE)

    @property
    def age(self):
        return (date.today() - self.birthday) // timedelta(days=365.2425)

    @property
    def short_name(self):
        if self.patronymic is not None and self.patronymic != '':
            return '%s %s %s' % (self.surname, self.name[0], self.patronymic[0])
        else:
            return '%s %s.' % (self.surname, self.name[0])

    @property
    def short_info(self):
        return '%s (ОМС № %s)' % (self.short_name, self.omi_card)

    @property
    def full_name(self):
        if self.patronymic is not None and self.patronymic != '':
            return '%s %s %s' % (self.surname, self.name, self.patronymic)
        else:
            return '%s %s' % (self.surname, self.name)

    def __str__(self):
        return self.short_info

    def __repr__(self):
        return self.short_info

    class Meta:
        db_table = 'patient'
        verbose_name = _('Пациент')
        verbose_name_plural = _('Пациенты')


class BaseMedType(AbstractModel):
    name = models.CharField(max_length=200, verbose_name=_('Название'))
    short_name = models.CharField(max_length=200, unique=True, blank=True, null=True, verbose_name=_('Идентификатор'))
    description = models.CharField(max_length=255, blank=True, null=True, verbose_name=_('Описание'))

    def __str__(self):
        return self.name

    class Meta:
        abstract = True


class MedArea(BaseMedType):
    parent = models.ForeignKey('core.MedArea', blank=True, null=True)

    def save(self, *args, **kwargs):
        if self.short_name is None or self.short_name == '':
            self.short_name = translit(self.name, 'ru', reversed=True).lower().replace(' ', '_')
        super(MedArea, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'med_area'
        verbose_name = _('Медицинская область')
        verbose_name_plural = _('Медицинские области')


class MedTest(BaseMedType):
    med_area = models.ForeignKey('core.MedArea')

    def save(self, *args, **kwargs):
        if self.short_name is None or self.short_name == '':
            self.short_name = self.med_area.short_name + '_' + translit(self.name, 'ru', reversed=True).lower().replace(' ', '_')
        super(MedTest, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'med_test'
        verbose_name = _('Тип обследования')
        verbose_name_plural = _('Типы обследования')


class RealInd(BaseMedType):
    med_test = models.ForeignKey('core.MedTest', related_name='real_inds')
    min_norm = models.FloatField(blank=True, null=True, verbose_name=_('Минимальная норма'))
    max_norm = models.FloatField(blank=True, null=True, verbose_name=_('Максимальная норма'))
    min_critical = models.FloatField(blank=True, null=True, verbose_name=_('Минимальная критическая норма'))
    max_critical = models.FloatField(blank=True, null=True, verbose_name=_('Максимальная критическая норма'))
    unit = models.CharField(max_length=20, blank=True, null=True, verbose_name=_('Единица измерения'))

    class Meta:
        db_table = 'real_ind'
        verbose_name = _('Вещественный показатель')
        verbose_name_plural = _('Вещественные показатели')

    def save(self, *args, **kwargs):
        if self.min_norm is None or self.max_norm is None:
            pass
        elif self.min_norm > self.max_norm:
            raise ValidationError("Min norm must be less than max norm")
        if self.short_name is None or self.short_name == '':
            self.short_name = self.med_test.short_name + '_' + translit(self.name, 'ru', reversed=True).lower().replace(' ', '_')
        super(RealInd, self).save(*args, **kwargs)


class IntInd(BaseMedType):
    med_test = models.ForeignKey('core.MedTest', related_name='int_inds')
    min_norm = models.IntegerField(blank=True, null=True, verbose_name=_('Минимальная норма'))
    max_norm = models.IntegerField(blank=True, null=True, verbose_name=_('Максимальная норма'))
    min_critical = models.IntegerField(blank=True, null=True, verbose_name=_('Минимальная критическая норма'))
    max_critical = models.IntegerField(blank=True, null=True, verbose_name=_('Максимальная критическая норма'))
    unit = models.CharField(max_length=20, blank=True, null=True, verbose_name=_('Единица измерения'))

    class Meta:
        db_table = 'int_ind'
        verbose_name = _('Целый показатель')
        verbose_name_plural = _('Целые показатели')

    def save(self, *args, **kwargs):
        if self.min_norm is None or self.max_norm is None:
            pass
        elif self.min_norm > self.max_norm:
            raise ValidationError("Min norm must be less than max norm")
        if self.short_name is None or self.short_name == '':
            self.short_name = self.med_test.short_name + '_' + translit(self.name, 'ru', reversed=True).lower().replace(' ', '_')
        super(IntInd, self).save(*args, **kwargs)


class TextInd(BaseMedType):
    med_test = models.ForeignKey('core.MedTest', related_name='text_inds')
    values = ArrayField(models.CharField(max_length=255), null=True, blank=True, verbose_name=_('Принимаемые значения'))

    class Meta:
        db_table = 'text_ind'
        verbose_name = _('Строковой показатель')
        verbose_name_plural = _('Строковые показатели')

    def save(self, *args, **kwargs):
        if self.short_name is None or self.short_name == '':
            self.short_name = self.med_test.short_name + '_' + translit(self.name, 'ru', reversed=True).lower().replace(' ', '_')
        super(TextInd, self).save(*args, **kwargs)


class TestRec(AbstractModel):

server/api/apps/core/forms.py
from django.contrib.admin import TabularInline
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from apps.core.models import User, IntInd, RealInd, TextInd


class CustomUserCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

    class Meta:
        model = User
        fields = ('email',)


class CustomUserChangeForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super(CustomUserChangeForm, self).__init__(*args, **kwargs)

    class Meta:
        model = User
        fields = ('email',)


class RealIndInline(TabularInline):
    model = RealInd
    extra = 0


class IntIndInline(TabularInline):
    model = IntInd
    extra = 0


class TextIndInline(TabularInline):
    model = TextInd
    extra = 0

server/api/apps/core/views.py
from django.shortcuts import render

# Create your views here.

server/api/templates/core/analytics_sidebar.html
{% extends 'core/base_menu_fluid.html' %}
{% block header %}
    <style>
        body {
            padding-top: 80px;
        }

        .bg-light {
            background-color: #f8f9fa !important;
        }

        .d-sm-block {
            display: block !important;
        }

        .d-sm-block {
            display: block !important;
        }

        .flex-column {
            -ms-flex-direction: column !important;
            flex-direction: column !important;
        }

        .sidebar {
            padding-left: 0;
            padding-right: 0;
        }

        .sidebar {
            position: fixed;
            top: 51px;
            bottom: 0;
            left: 0;
            z-index: 1000;
            padding-top: 10px;
            overflow-x: hidden;
            overflow-y: auto;
            border-right: 1px solid #eee;
        }

        .sidebar .nav-item {
            width: 100%;
        }

        .nav {
            display: -ms-flexbox;
            display: flex;
            -ms-flex-wrap: wrap;
            flex-wrap: wrap;
            padding-left: 0;
            margin-bottom: 0;
            list-style: none;
        }

        .link {
            display: block;
            padding: .5rem 1rem;
        }

        .sidebar .link {
            border-radius: 0;
        }

        .nav-item > a {
            border-bottom: 1px solid #e1e4e8;
        }

        .nav-pills > li + li {
            margin-left: 0;
        }

        .nav-pills > li.active > a, .nav-pills > li.active > a:focus, .nav-pills > li.active > a:hover {
            border-left: 4px solid #e36209;
            background-color: #eee;
            color: #0f0f0f;
        }

        .counter {
            display: inline-block;
            padding: 2px 5px;
            font-size: 12px;
            font-weight: 600;
            line-height: 1;
            color: #586069;
            background-color: rgba(27, 31, 35, 0.08);
            border-radius: 20px;
        }

        main {
            margin-left: 240px;
        }

        h1 {
            margin-bottom: 20px;
            padding-bottom: 9px;
            border-bottom: 1px solid #eee;
        }
    </style>
{% endblock %}

{% block header2 %}

{% endblock %}

{% block content %}
    <div class="row">
        <nav class="col-sm-3 col-md-2 d-none d-sm-block bg-light sidebar">
            <ul class="nav nav-pills flex-column">
                <li id="id_datasets_nav_item">
                    <a data-target="#" href="#" onclick="window.location='{% url 'analytics:datasets' %}'" class="link">Датасеты</a>
                </li>
                <li id="id_visualization_nav_item">
                    <a data-target="#" href="#" onclick="window.location='{% url 'analytics:visualization' %}'" class="link">Визуализация</a>
                </li>
                <li id="id_clustering_nav_item">
                    <a data-target="#" href="#" onclick="window.location='{% url 'analytics:clustering' %}'" class="link">Кластеризация</a>
                </li>
            </ul>
        </nav>
        <main class="col-sm-9 ml-sm-auto col-md-10 pt-3 tab-content">
            {% block main %}
            {% endblock %}
        </main>
    </div>
{% endblock %}

server/api/templates/core/base_menu.html
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}"/>
        {% block header %}
        {% endblock %}
    </head>
    <body>
        <script type="text/javascript" src="{% static 'jquery/jquery.js' %}"></script>
        <div class="container">
            <nav class="navbar navbar-inverse navbar-fixed-top">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <div class="navbar-brand">ReactMed</div>
                    </div>
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'main:about' %}">О сайте</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">Справочная информация <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'main:help' %}">Помощь</a></li>
                                 <li><a href="{% url 'main:med_tests_help' %}">Медицинские обследования</a></li>
                            </ul>
                        </li>
                        <li><a href="{% url 'patients:list' %}">Пациенты</a></li>
                        <li><a href="{% url 'analytics:visualization' %}">Анализ данных</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                               aria-expanded="false">
                                <span class="glyphicon glyphicon-user"></span>
                                Профиль <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'users:show' %}">Личная страница</a></li>
                                <li><a href="#">Настройки</a></li>
                                <li><a href="#">Помощь</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="{% url 'users:logout' %}">Выйти</a></li>
                            </ul>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
            </nav>
            {% block content %}
            {% endblock content %}
        </div>
        <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        {% block scripts %}
        {% endblock %}
    </body>
</html>

server/api/templates/core/base_menu_fluid.html
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}"/>
        <script type="text/javascript" src="{% static 'jquery/jquery.js' %}"></script>
        <link rel="stylesheet" href="{% static 'bootstrap-multiselect/dist/css/bootstrap-multiselect.css' %}">
        <script src="{% static 'bootstrap-multiselect/dist/js/bootstrap-multiselect.js' %}"></script>
        <link rel="stylesheet" href="{% static 'tokenfield/css/bootstrap-tokenfield.min.css' %}">
        <script src="{% static 'tokenfield/bootstrap-tokenfield.min.js' %}"></script>
        {% block header %}
        {% endblock %}
    </head>
    <body>
        <div class="container-fluid">
            <nav class="navbar navbar-inverse navbar-fixed-top">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <div class="navbar-brand">ReactMed</div>
                    </div>
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'main:about' %}">О сайте</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">Справочная информация <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'main:help' %}">Помощь</a></li>
                                <li><a href="{% url 'main:med_tests_help' %}">Медицинские обследования</a></li>
                            </ul>
                        </li>
                        <li><a href="{% url 'patients:list' %}">Пациенты</a></li>
                        <li><a href="{% url 'analytics:visualization' %}">Анализ данных</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                               aria-expanded="false">
                                <span class="glyphicon glyphicon-user"></span>
                                Профиль <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'users:show' %}">Личная страница</a></li>
                                <li><a href="#">Настройки</a></li>
                                <li><a href="#">Помощь</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="{% url 'users:logout' %}">Выйти</a></li>
                            </ul>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
            </nav>
            {% block content %}
            {% endblock content %}
        </div>
        <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        {% block scripts %}
        {% endblock %}
    </body>
</html>