server/api/api/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include('apps.api.urls', namespace='api')),
    url(r'', include('apps.main.urls', namespace='main')),
    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^patients/', include('apps.patients.urls', namespace='patients')),
    url(r'^med_tests/', include('apps.med_tests.urls', namespace='med_tests')),
    url(r'^appointments/', include('apps.appointments.urls', namespace='appointments')),
    url(r'^diagnosis/', include('apps.diagnosis.urls', namespace='diagnosis')),
    url(r'^reports/', include('apps.reports.urls', namespace='reports')),
    url(r'^analytics/', include('apps.analytics.urls', namespace='analytics'))
]

server/api/apps/main/urls.py
from django.conf.urls import url
from apps.main.views import *

urlpatterns = [
    url(r'^$', index_view, name='index'),
    url(r'^about$', about_view, name='about'),
    url(r'^help$', help_view, name='help'),
    url(r'^login$', login_view, name='login'),
    url(r'^help/med_tests/(?P<test_id>\d+)$', show_med_test_help, name='show_med_test_help'),
    url(r'^help/med_tests$', med_tests_help, name='med_tests_help'),
    url(r'^on_fail/login$', on_fail_login, name='on_fail_login')
]

server/api/apps/users/urls.py
from django.conf.urls import url
from apps.users.views import *

urlpatterns = [
    url(r'^show$', show_action, name='show'),
    url(r'^create$', create_action, name='create'),
    url(r'^update$', update_action, name='update'),
    url(r'^change_password$', change_password_action, name='change_password'),
    url(r'^reset_password$', reset_password_action, name='reset_password'),
    url(r'^delete$', delete_action, name='delete'),
    url(r'^logout$', logout_action, name='logout'),
    url(r'^dashboard$', dashboard_action, name='dashboard')
]

server/api/apps/core/models.py
# -*- coding: utf-8 -*- 
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.contrib.postgres.fields import *
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _
from transliterate import translit
from datetime import date, timedelta
from django.conf import settings

from apps.core.managers import UserManager

GENDER = (
    ('Мужской', 'Мужской'),
    ('Женский', 'Женский')
)

BLOOD_GROUP = (
    ('I', 'I'),
    ('II', 'II'),
    ('III', 'III'),
    ('IV', 'IV')
)

RH_FACTOR = (
    ('Rh+', 'Rh+'),
    ('Rh-', 'Rh-')
)

APPOINTMENT_STATUS = (
    ('Назначено', 'Назначено'),
    ('Завершено', 'Завершено'),
    ('Отменено', 'Отменено')
)

DIAGNOSIS_TYPE = (
    ('Предварительный', 'Предварительный'),
    ('Клинический', 'Клинический'),
    ('Окончательный', 'Окончательный')
)

USER_ROLES = (
    ('ADMIN', 'ADMIN'),
    ('DOCTOR', 'DOCTOR')
)


class AbstractModel(models.Model):
    id = models.AutoField(primary_key=True)

    class Meta:
        abstract = True


class User(AbstractBaseUser, PermissionsMixin):
    email = models.CharField(verbose_name=_('Email'), max_length=30, unique=True)
    name = models.CharField(verbose_name=_('Имя'), max_length=30)
    surname = models.CharField(verbose_name=_('Фамилия'), max_length=30)
    patronymic = models.CharField(verbose_name=_('Отчество'), max_length=30, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(_('Администратор?'), default=False)
    date_joined = models.DateTimeField(default=now())
    role = models.CharField(verbose_name=_('Роль'), max_length=20, choices=USER_ROLES, default='DOCTOR')

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        db_table = 'user'
        verbose_name = _('Пользователь')
        verbose_name_plural = _('Пользователи')

    def get_short_name(self):
        return '%s %s' % (self.name, self.surname)

    def get_full_name(self):
        return '%s' % self.name


class Address(AbstractModel):
    post_code = models.CharField(max_length=30, verbose_name='Post code')
    country = models.CharField(max_length=100, verbose_name='Country')
    region = models.CharField(max_length=100, verbose_name='Region')
    city = models.CharField(max_length=100, verbose_name='City')
    street = models.CharField(max_length=150, verbose_name='Street')

    class Meta:
        db_table = 'address'
        verbose_name = _('Address')
        verbose_name_plural = _('Addresses')


class OmiCard(AbstractModel):
    number = models.CharField(max_length=16, verbose_name='Number')
    expire_date = models.DateField(verbose_name='Expiration date')
    insurance_org = models.CharField(max_length=150, verbose_name='Insurance Organization')

    class Meta:
        db_table = 'omi_card'
        verbose_name = _('OMI Card')
        verbose_name_plural = _('OMI Cards')


class Patient(AbstractModel):
    name = models.CharField(verbose_name=_('Имя'), max_length=50)
    surname = models.CharField(verbose_name=_('Фамилия'), max_length=50)
    patronymic = models.CharField(verbose_name=_('Отчество'), max_length=50, blank=True, null=True)
    gender = models.CharField(verbose_name=_('Пол'), max_length=20, choices=GENDER)
    birthday = models.DateField(verbose_name=_('Дата рождения'))
    blood_group = models.CharField(verbose_name=_('Группа крови'), max_length=20, choices=BLOOD_GROUP, blank=True,
                                   null=True)
    rh_factor = models.CharField(verbose_name=_('Резус-фактор'), max_length=20, choices=RH_FACTOR, blank=True, null=True)
    is_disabled = models.BooleanField(verbose_name=_('Инвалидность'), default=False)
    omi_card = models.CharField(verbose_name=_('ОМС'), max_length=30, blank=True, null=True)
    address = models.CharField(verbose_name=_('Адрес проживания'), max_length=255, blank=True, null=True)
    occupation = models.CharField(verbose_name=_('Род деятельности'), max_length=100, blank=True, null=True)
    doctor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='patients', on_delete=models.CASCADE)

    @property
    def age(self):
        return (date.today() - self.birthday) // timedelta(days=365.2425)

    @property
    def short_name(self):
        if self.patronymic is not None and self.patronymic != '':
            return '%s %s %s' % (self.surname, self.name[0], self.patronymic[0])
        else:
            return '%s %s.' % (self.surname, self.name[0])

    @property
    def short_info(self):
        return '%s (ОМС № %s)' % (self.short_name, self.omi_card)

    @property
    def full_name(self):
        if self.patronymic is not None and self.patronymic != '':
            return '%s %s %s' % (self.surname, self.name, self.patronymic)
        else:
            return '%s %s' % (self.surname, self.name)

    def __str__(self):
        return self.short_info

    def __repr__(self):
        return self.short_info

    class Meta:
        db_table = 'patient'
        verbose_name = _('Пациент')
        verbose_name_plural = _('Пациенты')


class BaseMedType(AbstractModel):
    name = models.CharField(max_length=200, verbose_name=_('Название'))
    short_name = models.CharField(max_length=200, unique=True, blank=True, null=True, verbose_name=_('Идентификатор'))
    description = models.CharField(max_length=255, blank=True, null=True, verbose_name=_('Описание'))

    def __str__(self):
        return self.name

    class Meta:
        abstract = True


class MedArea(BaseMedType):
    parent = models.ForeignKey('core.MedArea', blank=True, null=True)

    def save(self, *args, **kwargs):
        if self.short_name is None or self.short_name == '':
            self.short_name = translit(self.name, 'ru', reversed=True).lower().replace(' ', '_')
        super(MedArea, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'med_area'
        verbose_name = _('Медицинская область')
        verbose_name_plural = _('Медицинские области')


class MedTest(BaseMedType):
    med_area = models.ForeignKey('core.MedArea')

    def save(self, *args, **kwargs):
        if self.short_name is None or self.short_name == '':
            self.short_name = self.med_area.short_name + '_' + translit(self.name, 'ru', reversed=True).lower().replace(' ', '_')
        super(MedTest, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'med_test'
        verbose_name = _('Тип обследования')
        verbose_name_plural = _('Типы обследования')


class RealInd(BaseMedType):
    med_test = models.ForeignKey('core.MedTest', related_name='real_inds')
    min_norm = models.FloatField(blank=True, null=True, verbose_name=_('Минимальная норма'))
    max_norm = models.FloatField(blank=True, null=True, verbose_name=_('Максимальная норма'))
    min_critical = models.FloatField(blank=True, null=True, verbose_name=_('Минимальная критическая норма'))
    max_critical = models.FloatField(blank=True, null=True, verbose_name=_('Максимальная критическая норма'))
    unit = models.CharField(max_length=20, blank=True, null=True, verbose_name=_('Единица измерения'))

    class Meta:
        db_table = 'real_ind'
        verbose_name = _('Вещественный показатель')
        verbose_name_plural = _('Вещественные показатели')

    def save(self, *args, **kwargs):
        if self.min_norm is None or self.max_norm is None:
            pass
        elif self.min_norm > self.max_norm:
            raise ValidationError("Min norm must be less than max norm")
        if self.short_name is None or self.short_name == '':
            self.short_name = self.med_test.short_name + '_' + translit(self.name, 'ru', reversed=True).lower().replace(' ', '_')
        super(RealInd, self).save(*args, **kwargs)


class IntInd(BaseMedType):
    med_test = models.ForeignKey('core.MedTest', related_name='int_inds')
    min_norm = models.IntegerField(blank=True, null=True, verbose_name=_('Минимальная норма'))
    max_norm = models.IntegerField(blank=True, null=True, verbose_name=_('Максимальная норма'))
    min_critical = models.IntegerField(blank=True, null=True, verbose_name=_('Минимальная критическая норма'))
    max_critical = models.IntegerField(blank=True, null=True, verbose_name=_('Максимальная критическая норма'))
    unit = models.CharField(max_length=20, blank=True, null=True, verbose_name=_('Единица измерения'))

    class Meta:
        db_table = 'int_ind'
        verbose_name = _('Целый показатель')
        verbose_name_plural = _('Целые показатели')

    def save(self, *args, **kwargs):
        if self.min_norm is None or self.max_norm is None:
            pass
        elif self.min_norm > self.max_norm:
            raise ValidationError("Min norm must be less than max norm")
        if self.short_name is None or self.short_name == '':
            self.short_name = self.med_test.short_name + '_' + translit(self.name, 'ru', reversed=True).lower().replace(' ', '_')
        super(IntInd, self).save(*args, **kwargs)


class TextInd(BaseMedType):
    med_test = models.ForeignKey('core.MedTest', related_name='text_inds')
    values = ArrayField(models.CharField(max_length=255), null=True, blank=True, verbose_name=_('Принимаемые значения'))

    class Meta:
        db_table = 'text_ind'
        verbose_name = _('Строковой показатель')
        verbose_name_plural = _('Строковые показатели')

    def save(self, *args, **kwargs):
        if self.short_name is None or self.short_name == '':
            self.short_name = self.med_test.short_name + '_' + translit(self.name, 'ru', reversed=True).lower().replace(' ', '_')
        super(TextInd, self).save(*args, **kwargs)


class TestRec(AbstractModel):

server/api/apps/users/models.py
from django.db import models


class SignUp:
    pass

server/api/apps/users/forms.py
from django.contrib.auth import get_user_model, logout, login
from django.forms import *

User = get_user_model()


class SignUpForm(Form):
    name = CharField(max_length=50)
    surname = CharField(max_length=50)
    email = CharField(max_length=50)
    password = CharField(max_length=16)
    confirm_password = CharField(max_length=16)

    def is_valid(self):
        valid = super(SignUpForm, self).is_valid()
        if not valid:
            return False
        user = None
        try:
            user = User.objects.get(email=self.cleaned_data['email'])
        except User.DoesNotExist:
            pass
        if user is not None:
            self._errors['not_unique_email'] = 'User with email "%s" exists' % self.cleaned_data['email']
            return False
        if self.cleaned_data['password'] != self.cleaned_data['confirm_password']:
            self._errors['not_confirmed_password'] = 'Password is not confirmed'
            return False
        return True

    def create_account(self):
        email = self.cleaned_data['email']
        name = self.cleaned_data['name']
        surname = self.cleaned_data['surname']
        password = self.cleaned_data['password']
        user = User.objects.create_user(email=email, password=password, name=name, surname=surname)
        user.first_name = name
        user.last_name = surname
        user.save()


class UpdateUserForm(Form):
    name = CharField(max_length=50)
    surname = CharField(max_length=50)

    def __init__(self, request):
        super().__init__(data=request.POST)
        self.user = request.user

    def update(self):
        name = self.cleaned_data['name']
        surname = self.cleaned_data['surname']
        self.user.name = name
        self.user.surname = surname
        self.user.save()


class ChangePasswordForm(Form):
    current_password = CharField(max_length=16)
    new_password = CharField(max_length=16)
    confirm_new_password = CharField(max_length=16)

    def __init__(self, data, user):
        super().__init__(data)
        self.user = user

    def is_valid(self):
        valid = super(ChangePasswordForm, self).is_valid()
        current_password = self.cleaned_data['current_password']
        if not valid:
            return False
        if not self.user.check_password(current_password):
            return False
        new_password = self.cleaned_data['new_password']
        confirm_new_password = self.cleaned_data['confirm_new_password']
        if new_password != confirm_new_password:
            return False
        return True

    def change_password(self, request):
        self.user.set_password(self.cleaned_data['new_password'])
        self.user.save()
        logout(request=request)
        login(request=request, user=self.user)

server/api/apps/api/views/user_views.py
from django.http import JsonResponse
from rest_framework.generics import ListAPIView, RetrieveUpdateDestroyAPIView

from apps.core.models import User
from apps.api.serializers import UserSerializer


class UserListView(ListAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class UserView(RetrieveUpdateDestroyAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer


def check_login(request):
    if request.method == 'GET':
        username = request.GET.get('username')
        password = request.GET.get('password')
        try:
            user = User.objects.get(email=username)
        except User.DoesNotExist:
            return JsonResponse(data={'error': 'Пользователь с таким логином не существует!'})
        if not user.check_password(password):
            return JsonResponse(data={'error': 'Пароль введен неправильно!'})
    return JsonResponse(data={})

server/api/apps/users/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse

from apps.users.forms import SignUpForm, ChangePasswordForm, UpdateUserForm


def create_action(request):
    if request.method == 'GET':
        return render(request, 'users/create.html', {})
    elif request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.create_account()
            return redirect(reverse('main:index'))
        else:
            return redirect(reverse('users:create'))
    return redirect(reverse('main:index'))


@login_required
def show_action(request):
    return render(request, 'users/show.html', {})


@login_required
def update_action(request):
    form = UpdateUserForm(request=request)
    if form.is_valid():
        form.update()
    return redirect(reverse('users:show'))


@login_required
def change_password_action(request):
    if request.method == 'POST':
        user = request.user
        form = ChangePasswordForm(request.POST, user=user)
        if form.is_valid():
            form.change_password(request=request)
    return redirect(reverse('users:show'))


def reset_password_action(request):
    pass


@login_required
def delete_action(request):
    if request.method == 'POST':
        password = request.POST['current_password']
        user = request.user
        if user.check_password(password):
            user.delete()
            logout(request)
            return redirect(reverse('main:index'))
    return redirect(reverse('users:show'))


@login_required
def logout_action(request):
    logout(request)
    return redirect(reverse('main:index'))


@login_required()
def dashboard_action(request):
    patients = request.user.patients.all()
    return render(request, 'users/dashboard.html', {'patients': patients})

server/api/templates/users/create.html
{% load staticfiles %}
<html>
    <head>
        <title>Регистрация</title>
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}"/>
    </head>
    <body style="padding-top: 60px;">
        <div class="container">
            <nav class="navbar navbar-inverse navbar-fixed-top">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <div class="navbar-brand">ReactMed</div>
                    </div>
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'main:index' %}">Главная</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">Сайт <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'main:about' %}">О сайте</a></li>
                                <li><a href="">Помощь</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
            <h1 class="page-header">Регистрация</h1>
            <form class="form" method="post">
                {% csrf_token %}
{#                <div class="form-group row">#}
{#                    <label class="col-sm-2 form-control-label">Роль: </label>#}
{#                    <div class="col-sm-10">#}
{#                        <select class="form-control" id="sel1">#}
{#                            <option value="patient">Пациент</option>#}
{#                            <option value="doctor">Врач</option>#}
{#                            <option value="nurse">Медсестра</option>#}
{#                            <option value="hospital_admin">Администратор больницы</option>#}
{#                        </select>#}
{#                    </div>#}
{#                </div>#}
                <div class="form-group row">
                    <label for="id_name" class="col-sm-2 form-control-label">Имя: </label>
                    <div class="col-sm-10">
                        <input id="id_name" name="name" class="form-control" style="background-color: #ffffff"/>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_surname" class="col-sm-2 form-control-label">Фамилия: </label>
                    <div class="col-sm-10">
                        <input id="id_surname" name="surname" class="form-control" style="background-color: #ffffff"/>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_email" class="col-sm-2 form-control-label">Электронная почта: </label>
                    <div class="col-sm-10">
                        <input id="id_email" name="email" class="form-control" style="background-color: #ffffff"/>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_password" class="col-sm-2 form-control-label">Пароль: </label>
                    <div class="col-sm-10">
                        <input id="id_password" name="password" type="password" class="form-control" style="background-color: #ffffff"/>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="id_confirm_password" class="col-sm-2 form-control-label">Подтверждение пароля: </label>
                    <div class="col-sm-10">
                        <input id="id_confirm_password" name="confirm_password" type="password" class="form-control" style="background-color: #ffffff"/>
                    </div>
                </div>
                <div class="row pull-right">
                    <button class="btn btn-success">Регистрация</button>
                    <button class="btn btn-warning" type="reset">Отмена</button>
                </div>
            </form>
        </div>
    </body>
    <script type="text/javascript" src="{% static 'jquery/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</html>

server/api/templates/users/dashboard.html
{% extends 'core/base_menu_fluid.html' %}
{% load staticfiles %}
{% block header %}
    <style>
        body {
            padding-top: 80px;
        }

        .bg-light {
            background-color: #f8f9fa !important;
        }

        .d-sm-block {
            display: block !important;
        }

        .d-sm-block {
            display: block !important;
        }

        .flex-column {
            -ms-flex-direction: column !important;
            flex-direction: column !important;
        }

        .sidebar {
            padding-left: 0;
            padding-right: 0;
        }

        .sidebar {
            position: fixed;
            top: 51px;
            bottom: 0;
            left: 0;
            z-index: 1000;
            padding-top: 10px;
            overflow-x: hidden;
            overflow-y: auto;
            border-right: 1px solid #eee;
        }

        .sidebar .nav-item {
            width: 100%;
        }

        .nav {
            display: -ms-flexbox;
            display: flex;
            -ms-flex-wrap: wrap;
            flex-wrap: wrap;
            padding-left: 0;
            margin-bottom: 0;
            list-style: none;
        }

        .nav-link {
            display: block;
            padding: .5rem 1rem;
        }

        .sidebar .nav-link {
            border-radius: 0;
        }

        .nav-item > a {
            border-bottom: 1px solid #e1e4e8;
        }

        .nav-pills > li + li {
            margin-left: 0;
        }

        .nav-pills > li.active > a, .nav-pills > li.active > a:focus, .nav-pills > li.active > a:hover {
            border-left: 4px solid #e36209;
            background-color: #eee;
            color: #0f0f0f;
        }

        .counter {
            display: inline-block;
            padding: 2px 5px;
            font-size: 12px;
            font-weight: 600;
            line-height: 1;
            color: #586069;
            background-color: rgba(27, 31, 35, 0.08);
            border-radius: 20px;
        }

        main {
            margin-left: 240px;
        }

        h1 {
            margin-bottom: 20px;
            padding-bottom: 9px;
            border-bottom: 1px solid #eee;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="row">
        <nav class="col-sm-3 col-md-2 d-none d-sm-block bg-light sidebar">
            <ul class="nav nav-pills flex-column">
                <li class="nav-item active">
                    <a data-toggle="tab" href="#id_patients" class="nav-link">Пациенты <span
                            class="counter">{{ patients.count }}</span></a>
                </li>
                <li class="nav-item">
                    <a data-toggle="tab" href="#id_tests" class="nav-link">Обследования</a>
                </li>
                <li class="nav-item">
                    <a data-toggle="tab" href="#id_appointments" class="nav-link">Приемы</a>
                </li>
            </ul>
        </nav>
        <main class="col-sm-9 ml-sm-auto col-md-10 pt-3 tab-content">
            <div class="tab-pane active" id="id_patients">
                <div class="row">
                    <div class="col-xs-4">
                        <div class="input-group">
                            <input class="form-control" placeholder="ФИО пациента">
                            <span class="input-group-btn">
                                <button class="btn btn-success" type="button">Найти</button>
                            </span>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <button class="btn btn-success" onclick="window.location='{% url 'patients:create' %}'">Добавить
                            пациента
                        </button>
                    </div>
                </div>
                <br/>
                <table id="patients-table" class="table table-striped table-bordered table-hover" cellpadding="0" style="width: 100%; ">
                    <thead>
                        <tr>
                            <th>ОМС</th>
                            <th>ФИО</th>
                            <th>Пол</th>
                            <th>Возраст</th>
                            <th>Действия</th>
                        </tr>
                    </thead>
                    <tbody id="patients-table-body">
                        {% for patient in patients %}
                            <tr>
                                <td>
                                    № {{ patient.omi_card }}
                                </td>
                                <td>{{ patient.surname }} {{ patient.name }} {{ patient.patronymic|default_if_none:"" }}</td>
                                <td>{{ patient.gender }}</td>
                                <td>{{ patient.age }}</td>
                                <td>
                                    <a href="{% url 'patients:show' patient_id=patient.id %}" class="btn btn-success">
                                        <span class="glyphicon glyphicon-edit"></span>
                                    </a>
                                    <a href="{% url 'patients:delete' patient_id=patient.id %}" class="btn btn-danger">
                                        <span class="glyphicon glyphicon-remove"></span>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="tab-pane" id="id_tests">

            </div>
            <div class="tab-pane" id="id_appointments">

            </div>
        </main>
    </div>
{% endblock %}

server/api/templates/users/login.html
{% extends 'core/base_menu.html' %}
{% load staticfiles %}
{% block content %}

{% endblock %}